SELECT 
SPEC.ASSETNUM,
SPEC.ALNVALUE AS RANK,
A.DESCRIPTION AS ASSET_DESC,
CLASS.DESCRIPTION AS ASSET_CLASS,
LEFT(A.LOCATION,3) AS ASSET_DEPT 
FROM MAXIMO.ASSETSPEC SPEC
JOIN MAXIMO.ASSET A ON A.ASSETNUM = SPEC.ASSETNUM AND SPEC.SITEID = A.SITEID
JOIN MAXIMO.CLASSSTRUCTURE CLASS ON A.CLASSSTRUCTUREID = CLASS.CLASSSTRUCTUREID
WHERE SPEC.ASSETATTRID = 'A8539'
AND SPEC.SITEID = 'HMA' 
AND SPEC.ALNVALUE IN ('S','A','B','C')