/* Asset Attributes*/

SELECT A.ASSETNUM,
A.DESCRIPTION AS ASSET_DESC,
CL.DESCRIPTION AS ASSET_CLASS,
LEFT(A.LOCATION,3) AS ASSET_DEPT
FROM MAXIMO.ASSET A
JOIN MAXIMO.CLASSSTRUCTURE CL ON A.CLASSSTRUCTUREID = CL.CLASSSTRUCTUREID 
WHERE A.SITEID = 'HMA' AND A.STATUS = 'A-ACTIVE'