-- New script in maxdb76.
-- Date: Jan 13, 2025
-- Time: 8:35:58 AM
-- Purpose: Find all meters on assets in a certain area


/*Assets with Meters*/

SELECT AM.ASSETNUM,
A.DESCRIPTION AS ASSET_DESC,
AM.METERNAME ,
M.DESCRIPTION METERDESCRIPTION,
M.METERTYPE ,
AM.AVGCALCMETHOD ,
AM.ROLLDOWNSOURCE ,
AM.REMARKS ,
AM.POINTNUM ,
AM.LASTREADING ,
AM.LASTREADINGDATE AS LASTREADING_DATE,
AM.CHANGEBY ,
AM.LASTREADINGINSPCTR,
CL.DESCRIPTION AS CLASS,
LEFT(A.LOCATION,3) AS DEPT
FROM MAXIMO.ASSETMETER AM JOIN MAXIMO.ASSET A ON AM.ASSETNUM = A.ASSETNUM
JOIN MAXIMO.METER M ON AM.METERNAME = M.METERNAME
LEFT JOIN MAXIMO.CLASSSTRUCTURE CL ON A.CLASSSTRUCTUREID = CL.CLASSSTRUCTUREID 
WHERE A.SITEID = 'HMA' AND A.STATUS = 'A-ACTIVE'


