/* ACM Assets Dimension Table: from Routes */ 
SELECT R.ROUTE ,
R.DESCRIPTION AS ROUTE_DESC,
RS.ASSETNUM ,
A.DESCRIPTION AS ASSET_DESC,
CL.DESCRIPTION AS CLASS,
LEFT(A.LOCATION, 3) DEPT
FROM MAXIMO.ROUTE_STOP RS 
LEFT JOIN MAXIMO.ROUTES R ON R.ROUTE = RS.ROUTE AND R.SITEID =RS.SITEID 
LEFT JOIN MAXIMO.ASSET A ON RS.ASSETNUM = A.ASSETNUM AND RS.SITEID = A.SITEID 
LEFT JOIN MAXIMO.CLASSSTRUCTURE CL ON A.CLASSSTRUCTUREID = CL.CLASSSTRUCTUREID 
WHERE REGEXP_LIKE(R.DESCRIPTION, '^[A-Z0-9]+_[A-Z0-9]+_[A-Z0-9]+ - .+') 
AND RS.SITEID = 'HMA' AND A.STATUS = 'A-ACTIVE'